version: "3.9"

services:
  db:
    image: postgres:15
    container_name: todotask_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - heli-todo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo"]
      interval: 5s
      timeout: 3s
      retries: 5

  localstack:
    image: localstack/localstack
    container_name: todotask_localstack
    environment:
      SERVICES: sqs
      DEFAULT_REGION: us-east-1
      EDGE_PORT: 4566
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - heli-todo


  app:
    build: .
    container_name: todo_app
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=todo
      - DB_NAME=todo
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
    networks:
      - heli-todo

networks:
  heli-todo:

volumes:
  db_data:
  localstack_data:
